# Time series classification using Random Forest 

This notebook proposes a solution to the EY Open Science Data Challenge - Level 1, with the objective to identify rice fields in a region of Vietnam using only Sentinel 1 satellite VH and VV time series values.

In [ ]:
# Visualization
import ipyleaflet
import matplotlib.pyplot as plt
from IPython.display import Image
import seaborn as sns

# Data Science
import numpy as np
import pandas as pd
# Feature Engineering
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler, RobustScaler
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

# Machine Learning
from sklearn.metrics import f1_score, accuracy_score,classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression


# Planetary Computer Tools
import pystac
import pystac_client
from pystac_client import Client
from pystac.extensions.eo import EOExtension as eo
import odc
import toolz
from odc.stac import stac_load
import planetary_computer as pc
pc.settings.set_subscription_key('8e9b6659b924459a988554b473a6a8e7')

# Others
import requests
import rich.table
from itertools import cycle
from tqdm import tqdm
tqdm.pandas()


#Get vh_vv function

def get_sentinel_data(latlong,time_slice,assets):
    '''
    Returns VV and VH values for a given latitude and longitude 
    Attributes:
    latlong - A tuple with 2 elements - latitude and longitude
    time_slice - Timeframe for which the VV and VH values have to be extracted
    assets - A list of bands to be extracted
    '''

    latlong=latlong.replace('(','').replace(')','').replace(' ','').split(',')
    
    box_size_deg = 0.0009 # Surrounding box in degrees, yields approximately 5x5 pixel region

    min_lon = float(latlong[1])-box_size_deg/2
    min_lat = float(latlong[0])-box_size_deg/2
    max_lon = float(latlong[1])+box_size_deg/2
    max_lat = float(latlong[0])+box_size_deg/2

    bbox_of_interest = (min_lon, min_lat, max_lon, max_lat)
    #bbox_of_interest = (float(latlong[1]) , float(latlong[0]), float(latlong[1]) , float(latlong[0]))
    
    time_of_interest = time_slice

    catalog = pystac_client.Client.open(
        "https://planetarycomputer.microsoft.com/api/stac/v1",
        modifier=pc.sign_inplace,
    )
    search = catalog.search(
        collections=["sentinel-1-rtc"], bbox=bbox_of_interest, datetime=time_of_interest
    )
    items = list(search.get_all_items())
    
    
    
    # Define the pixel resolution for the final product
    # Define the scale according to our selected crs, so we will use degrees

    resolution = 10  # meters per pixel 
    scale = resolution / 111320.0 # degrees per pixel for crs=4326 
    
    # Load the data using Open Data Cube
    data = stac_load(items,bands=["vv", "vh"], patch_url=pc.sign, bbox=bbox_of_interest, crs="EPSG:4326", resolution=scale)
   
    # Calculate the mean of the data across the sample region
    mean = data.mean(dim=['latitude','longitude']).compute()
    
    # Calculate V
    v = mean.vv + mean.vh
    
    
    return v.values

def get_new_features(data,L):
    #data = 600 time series list of values
    
    
    new_features=[]
    if 'mean' in L:
        the_means=[]
        for col in data.columns:
            mean_v = float(np.mean(data[col]))
            the_means.append(mean_v)
        new_features.append(the_means)
    
    if 'std' in L:
        the_stds=[]
        for col in data.columns:
            sigma_v = float(np.std(data[col]))
            the_stds.append(sigma_v)
        new_features.append(the_stds)
    
    if 'CV' in L:
        the_CVs=[]
        for col in data.columns:
            mean_v = float(np.mean(data[col]))
            sigma_v = float(np.std(data[col]))
            CV_v = float(mean_v/sigma_v)
            the_CVs.append(CV_v)
        new_features.append(the_CVs)
    
    if 'max' in L:
        the_maxs=[]
        for col in data.columns:
            max_v = float(max(data[col]))
            the_maxs.append(max_v)
        new_features.append(the_maxs)
        
    if 'min' in L:
        the_mins=[]
        for col in data.columns:
            min_v = float(min(data[col]))
            the_mins.append(min_v)
        new_features.append(the_mins)
        
    if 'median' in L:
        the_medians=[]
        for col in data.columns:
            median_v = float(np.median(data[col]))
            the_medians.append(median_v)
        new_features.append(the_medians)
    
    if 'amplitude' in L:
        the_amplis=[]
        for col in data.columns:
            max_v = float(max(data[col]))
            min_v = float(min(data[col]))
            ampli_v = abs(max_v-min_v)
            the_amplis.append(ampli_v)
        new_features.append(the_amplis)
        
    if 'absolute energy' in L:
        the_abs_Es=[]
        for col in data.columns:
            abs_E_v = float(sum((data[col])**2))
            the_abs_Es.append(abs_E_v)
        new_features.append(the_abs_Es)
    
    if 'mean diff' in L:
        the_mean_diffs=[]
        col_1 = np.delete(data[col].values,0)
        col_2 = np.delete(data[col].values,len(data[col])-1)
        delta_v = col_1-col_2
        for col in data.columns:
            mean_delta_v = float(np.mean(delta_v))
            the_mean_diffs.append(mean_delta_v)
        new_features.append(the_mean_diffs)
        
    if 'autocorrelation lag 1' in L:
        the_auto_lag_1s=[]
        for col in data.columns: 
            the_auto=sm.tsa.acf(data[col])[1]
            the_auto_lag_1s.append(the_auto)
        new_features.append(the_auto_lag_1s)
    
    #median_delta_v = float(np.median(delta_v))
    #sum_delta_v = float(sum(abs(delta_v)))
    #dist_v = float(sum(np.sqrt(1+delta_v**2)))#signal distance 
    
    return np.transpose(pd.DataFrame(new_features))
        
        
def combine_two_datasets(dataset1,dataset2):
    '''
    Returns a  vertically concatenated dataset.
    Attributes:
    dataset1 - Dataset 1 to be combined 
    dataset2 - Dataset 2 to be combined
    '''
    data = pd.concat([dataset1,dataset2], axis=1)
    return data

def plot_confusion_matrix(true_value,predicted_value,title,labels):
    '''
    Plots a confusion matrix.
    Attributes:
    true_value - The ground truth value for comparision.
    predicted_value - The values predicted by the model.
    title - Title of the plot.
    labels - The x and y labels of the plot.
    '''
    cm = confusion_matrix(true_value,predicted_value)
    ax= plt.subplot()
    sns.heatmap(cm, annot=True, fmt='g', ax=ax, cmap='Blues');
    ax.set_xlabel('Predicted labels');
    ax.set_ylabel('True labels'); 
    ax.set_title(title); 
    ax.xaxis.set_ticklabels(labels); 
    ax.yaxis.set_ticklabels(labels);

In [ ]:
#Load the crop locations
crop_presence_data = pd.read_csv("Crop_Location_Data.csv")
crop_presence_data.head()

## Index and box size choice
The first step was to choose wisely a vegetation index as a combination of VV and VH values. By plotting several indexes (RVI, SNI, vh+vv, vh-vv, vh/vv and vh+vv/vh-vv) for a single day, the difference between the 'Non Rice' and 'Rice' values could be analyzed. The vh+vv values gave the best results and were therefore chosen.

The second parameter to choose was the box size on which the VV and VH values would be averaged in order to prevent overfitting. By testing 3x3, 5x5, 7x7, 8x8, 9x9, 10x10 and 11x11 box sizes, the best accuracy results were obtained with a box of 10x10.

Finally, a whole year of Sentinel 1 remote sensing was taken to build time series with enough data points.

In [ ]:
 # Function call to extract VV,VH Values
time_slice = "2020-01-01/2020-12-31"
assests = ['vh','vv']
list_v = []
for coordinates in tqdm(crop_presence_data['Latitude and Longitude']):
    v=get_sentinel_data(coordinates,time_slice,assests)
    list_v.append(v)
list_v = np.transpose(pd.DataFrame(list_v))

In [ ]:
#Use this box if you have already saved the extracted time series in a csv file

#list_v.to_csv('list_vh+vv_mean10x10.csv', index=False)
#list_v = pd.read_csv('list_vh+vv_mean10x10.csv')
list_v

## Feature extraction

This step constitute the main work of the project. A function (named get_new_features) was created to compute basic and more complex characteristics of the time series in order to better classify them. Selected features include the mean, the standard deviation, the absolute energy, the median, the amplitude, the maximum, the minimum, the coefficient of variation (CV), the autocorrelation lag 1 and the mean value differences.

In [ ]:
list_vf=get_new_features(list_v,['mean','std','median','amplitude','max','min','CV', 'absolute energy','autocorrelation lag 1'])
list_vf

,0,1,2,3,4,5,6,7
0,0.150443,0.081389,1.848439,0.417898,0.033809,0.141866,2.662399,0.668619
1,0.161405,0.093622,1.724010,0.397620,0.019632,0.143188,3.168313,0.503653
2,0.174756,0.091303,1.914012,0.423594,0.023404,0.159321,3.537714,0.561863
3,0.151072,0.083205,1.815663,0.374484,0.021534,0.139438,2.706856,0.664842
4,0.171708,0.101358,1.694067,0.466690,0.025129,0.139822,3.617900,0.460578
...,...,...,...,...,...,...,...,...
595,0.358064,0.053644,6.674886,0.457498,0.238119,0.368342,11.928982,-0.284864
596,0.388580,0.054431,7.138969,0.502198,0.250675,0.396880,14.010112,-0.274226
597,0.385577,0.051896,7.429866,0.522880,0.260889,0.385974,13.773989,-0.170827
598,0.378919,0.048853,7.756335,0.515207,0.288112,0.368814,13.282945,-0.067768
599,0.371443,0.041006,9.058196,0.482095,0.296542,0.369814,12.708275,0.182523

In [ ]:
pd.set_option('display.max_rows', 10)
list_vf

In [ ]:
list_vf[0].plot()

## Anomaly detection

By comparing to the submission dataset values, some of the training set values reach very large values. An attempt to remove those 'anomalies' has been done in order to be closer to the final submission dataset, but this has not improved the accuracy.

In [ ]:
#anomaly detection: for best score, do not execute
to_drop=[]
for i in range(np.shape(list_vf)[0]):
    for j in range(np.shape(list_vf)[1]):
        if abs(list_vf[j][i])>=70:
            to_drop.append(i)
list_vf=list_vf.drop(index=list_vf.index[to_drop])
crop_presence_data=crop_presence_data.drop(index=crop_presence_data.index[to_drop])
list_vf=list_vf.reset_index(drop=True)
crop_presence_data=crop_presence_data.reset_index(drop=True)

In [ ]:
#Combine Latitude, Longitude and VV/VH
crop_data = combine_two_datasets(crop_presence_data,list_vf)

In [ ]:
#Model building
#crop_data = crop_data[['vh','vv','Class of Land']]
X = crop_data.drop(columns=['Class of Land','Latitude and Longitude']).values
y = crop_data ['Class of Land'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify=y,random_state=50)

## Feature Scaling

Various scaling methods have been tested, including the StandardScaler, MinMaxScaler, MaxAbsScaler, and RobustScaler. The scaling method with the best results was the StandardScaler.

In [ ]:
#Feature scaling 1
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Feature scaling 2
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Feature scaling 3
sc = MaxAbsScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Feature scaling 4
sc = RobustScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Classification model selection

Several classification models have been tested, but the Random Forest Classifier has given the best results so far.

In [ ]:
model = LogisticRegression(solver='lbfgs')
model.fit(X_train,y_train)

In [ ]:
from sklearn import svm
model = svm.SVC(kernel='linear')
model.fit(X_train,y_train)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(n_estimators=500,learning_rate=0.01)
model.fit(X_train,y_train)

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
model=ExtraTreesClassifier(n_estimators=500)
model.fit(X_train,y_train)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=4)
model.fit(X_train,y_train)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=400)
model.fit(X_train,y_train)

In [ ]:
#Out sample evaluation
outsample_predictions = model.predict(X_test)
print("Accuracy {0:.2f}%".format(100*accuracy_score(outsample_predictions, y_test)))
#print(classification_report(y_test, outsample_predictions))
#plot_confusion_matrix(y_test, outsample_predictions,"Model Level 1: Logistic\nRegression Model Out-Sample Results",['Rice', 'Non Rice'])

Accuracy 100.00%

In [ ]:
#Submission test 
test_file = pd.read_csv('challenge_1_submission_template_correct_columns_fixed.csv')
test_file

                                           id  target
0     (10.18019073690894, 105.32022315786804)     NaN
1    (10.561107033461816, 105.12772097986661)     NaN
2    (10.623790611954897, 105.13771401411867)     NaN
3    (10.583364246115156, 105.23946127195805)     NaN
4     (10.20744446668854, 105.26844107128906)     NaN
..                                        ...     ...
245  (10.308283266873062, 105.50872812216863)     NaN
246  (10.582910017285496, 105.23991550078767)     NaN
247  (10.581547330796518, 105.23991550078767)     NaN
248  (10.629241357910818, 105.15315779432643)     NaN
249  (10.574733898351617, 105.10410108072531)     NaN

[250 rows x 2 columns]

In [ ]:
    
## Get Sentinel-1-RTC Data
time_slice = "2020-01-01/2020-12-31"
assests = ['vh','vv']
list_vs = []
for coordinates in tqdm(test_file['id']):
    vs=get_sentinel_data(coordinates,time_slice,assests)
    list_vs.append(vs)
submission_v_data = np.transpose(pd.DataFrame(list_vs))

In [ ]:
#Use this box if you have already saved the extracted time series in a csv file

#submission_v_data.to_csv('submission_vh+vv_ampli_mean10x10.csv', index=False)
#submission_v_data= pd.read_csv('submission_vh+vv_ampli_mean10x10.csv')
submission_v_data

,0,1,2,3,4,5,6,7,8,9,...,240,241,242,243,244,245,246,247,248,249
0,0.071010,0.090408,0.032390,0.011357,0.106483,0.012032,0.333144,0.019009,0.011706,0.135944,...,0.272086,0.032640,0.058736,0.275244,0.011324,0.012977,0.016263,0.011670,0.081528,0.063684
1,0.033210,0.090583,0.196563,0.015005,0.131743,0.033603,0.273232,0.356325,0.015543,0.200787,...,0.262989,0.026207,0.078842,0.361466,0.015188,0.019180,0.015442,0.013976,0.211229,0.074272
2,0.042691,0.051673,0.109337,0.011056,0.069317,0.020272,0.366986,0.355451,0.011411,0.078394,...,0.237198,0.029801,0.047675,0.315878,0.011364,0.018591,0.011856,0.013040,0.100126,0.212450
3,0.067287,0.091906,0.170209,0.017100,0.130884,0.026927,0.347514,0.084781,0.014450,0.102806,...,0.287416,0.042338,0.064058,0.274393,0.014673,0.347630,0.016230,0.013158,0.136282,0.229790
4,0.032429,0.076581,0.150962,0.014341,0.120224,0.029265,0.330509,0.056757,0.013585,0.070005,...,0.298752,0.028666,0.068215,0.282824,0.013482,0.020887,0.014590,0.014268,0.073500,0.233386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,0.051524,0.033642,0.173950,0.016183,0.059938,0.025426,0.343252,0.118525,0.015256,0.146872,...,0.314748,0.042286,0.128892,0.319389,0.015309,0.015892,0.015990,0.016278,0.262262,0.298291
87,0.070146,0.086459,0.214837,0.014217,0.133517,0.020393,0.435052,0.240663,0.015636,0.231419,...,0.359077,0.056390,0.020931,0.297483,0.015428,0.022114,0.014842,0.016362,0.262856,0.278087
88,0.031261,0.025858,0.222264,0.023472,0.276967,0.026330,0.327267,0.196700,0.024719,0.358286,...,0.265576,0.254141,0.062491,0.263373,0.022648,0.027791,0.021419,0.023372,0.186988,0.177172
89,0.024754,0.032737,0.390595,0.075006,0.333489,0.020214,0.340372,0.271634,0.051079,0.361941,...,0.300715,0.255815,0.071300,0.273560,0.054803,0.020302,0.025160,0.026728,0.592703,0.180666
90,0.208977,0.159743,0.225802,0.011125,0.234591,0.013884,0.382358,0.099872,0.011028,0.142737,...,0.343732,0.243769,0.285473,0.299871,0.010454,0.013316,0.011237,0.011155,0.122328,0.062119

In [ ]:
submission_v_data_f=get_new_features(submission_v_data,['mean','std','median','amplitude','max','min','CV','absolute energy', 'autocorrelation lag 1'])
submission_v_data_f

,0,1,2,3,4,5,6,7
0,0.143485,0.106808,1.343397,0.637004,0.009805,0.128950,2.911619,0.594340
1,0.135593,0.097921,1.384720,0.443915,0.012361,0.110139,2.545648,0.753440
2,0.147016,0.082185,1.788838,0.567111,0.022251,0.132523,2.581486,0.212406
3,0.018844,0.010111,1.863703,0.075092,0.011056,0.016395,0.041617,-0.060597
4,0.137145,0.081889,1.674776,0.362963,0.010686,0.120224,2.321835,0.568177
...,...,...,...,...,...,...,...,...
245,0.048182,0.090338,0.533352,0.606176,0.011762,0.021523,0.953905,0.177655
246,0.017641,0.004549,3.877756,0.031824,0.010893,0.016257,0.030202,0.048855
247,0.020214,0.015659,1.290893,0.129817,0.010889,0.016054,0.059499,-0.040554
248,0.177862,0.160243,1.109954,1.363649,0.035844,0.138337,5.215434,0.116873
249,0.142956,0.089797,1.592000,0.442673,0.022365,0.109101,2.593492,0.597837

In [ ]:
# Feature Scaling 
submission_v_data_f #= submission_vh_vv_data.values
transformed_submission_data = sc.transform(submission_v_data_f)

#Making predictions
final_predictions = model.predict(transformed_submission_data)
final_prediction_series = pd.Series(final_predictions)
    
#Combining the results into dataframe
submission_df = pd.DataFrame({'id':test_file['id'].values, 'target':final_prediction_series.values})
#Displaying the sample submission dataframe
display(submission_df)

                                           id    target
0     (10.18019073690894, 105.32022315786804)      Rice
1    (10.561107033461816, 105.12772097986661)      Rice
2    (10.623790611954897, 105.13771401411867)      Rice
3    (10.583364246115156, 105.23946127195805)  Non Rice
4     (10.20744446668854, 105.26844107128906)      Rice
..                                        ...       ...
245  (10.308283266873062, 105.50872812216863)  Non Rice
246  (10.582910017285496, 105.23991550078767)  Non Rice
247  (10.581547330796518, 105.23991550078767)  Non Rice
248  (10.629241357910818, 105.15315779432643)  Non Rice
249  (10.574733898351617, 105.10410108072531)      Rice

[250 rows x 2 columns]

In [ ]:
#Submission file
#Dumping the predictions into a csv file.
submission_df.to_csv("challenge_1_submission_rice_crop_prediction.csv",index = False)